In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://query.data.world/s/ckxg7aq4znw42ekv7vsndyq2ztj776')

In [3]:
df.head()

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
0,"Three saucer shaped ships. High in the sky, m...",Salem,OR,NaN,disk,15 minutes,Occurred : 8/15/1950 14:00 (Entered as : 08/1...,http://www.nuforc.org/webreports/135/S135871.html,"Three saucer shaped ships. High in the sky, m...",NaN,44.941247,-123.004235
1,Tear-drop shaped silent craft with sectional f...,Ellsworth,ME,NaN,teardrop,5 minutes,Occurred : 8/15/1967 21:30 (Entered as : 08/0...,http://www.nuforc.org/webreports/132/S132451.html,Tear-drop shaped silent craft with sectional f...,NaN,44.651300,-68.450700
2,Green orb shot out of white light ((NUFORC No...,San Antonio,TX,2017-01-25T20:45:00,light,90 minutes,Occurred : 1/25/2017 20:45 (Entered as : 01/2...,http://www.nuforc.org/webreports/132/S132305.html,Green orb shot out of white light I saw a whit...,2017-01-26T00:00:00,29.488866,-98.475240
3,Saw three circular orange lights traveling sou...,Port Saint Lucie,FL,2017-02-24T20:45:00,circle,5 minutes,Occurred : 2/24/2017 20:45 (Entered as : 02/2...,http://www.nuforc.org/webreports/132/S132890.html,Saw three circular orange lights traveling sou...,2017-03-10T00:00:00,27.285686,-80.363444
4,Light moving slowly thru the sky towards the W...,Whitefish,MT,2017-02-22T21:00:00,light,15 minutes,Occurred : 2/22/2017 21:00 (Entered as : 02/2...,http://www.nuforc.org/webreports/132/S132774.html,Light moving slowly thru the sky towards the w...,2017-03-10T00:00:00,48.411100,-114.337600

In [8]:
# drop rows with no lat or lng
ufo_locs = df.dropna(axis=0, how='any', thresh=None, subset=['city_latitude'], inplace=False)

In [9]:
ufo_locs = df.dropna(axis=0, how='any', thresh=None, subset=['city_longitude'], inplace=False)

In [10]:
ufo_locs.head(30)

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
0,"Three saucer shaped ships. High in the sky, m...",Salem,OR,NaN,disk,15 minutes,Occurred : 8/15/1950 14:00 (Entered as : 08/1...,http://www.nuforc.org/webreports/135/S135871.html,"Three saucer shaped ships. High in the sky, m...",NaN,44.941247,-123.004235
1,Tear-drop shaped silent craft with sectional f...,Ellsworth,ME,NaN,teardrop,5 minutes,Occurred : 8/15/1967 21:30 (Entered as : 08/0...,http://www.nuforc.org/webreports/132/S132451.html,Tear-drop shaped silent craft with sectional f...,NaN,44.651300,-68.450700
2,Green orb shot out of white light ((NUFORC No...,San Antonio,TX,2017-01-25T20:45:00,light,90 minutes,Occurred : 1/25/2017 20:45 (Entered as : 01/2...,http://www.nuforc.org/webreports/132/S132305.html,Green orb shot out of white light I saw a whit...,2017-01-26T00:00:00,29.488866,-98.475240
3,Saw three circular orange lights traveling sou...,Port Saint Lucie,FL,2017-02-24T20:45:00,circle,5 minutes,Occurred : 2/24/2017 20:45 (Entered as : 02/2...,http://www.nuforc.org/webreports/132/S132890.html,Saw three circular orange lights traveling sou...,2017-03-10T00:00:00,27.285686,-80.363444
4,Light moving slowly thru the sky towards the W...,Whitefish,MT,2017-02-22T21:00:00,light,15 minutes,Occurred : 2/22/2017 21:00 (Entered as : 02/2...,http://www.nuforc.org/webreports/132/S132774.html,Light moving slowly thru the sky towards the w...,2017-03-10T00:00:00,48.411100,-114.337600
6,((HOAX??)) Loud boom heard.,Duxbury,MA,2017-01-31T06:00:00,unknown,2,Occurred : 1/31/2017 06:00 (Entered as : 01/3...,http://www.nuforc.org/webreports/132/S132401.html,Loud boom heard. ((NUFORC Note: Witness elect...,2017-02-03T00:00:00,42.049490,-70.693082
7,Two erratic bright white lights seen in Southe...,Studio City,CA,2017-01-29T10:34:00,light,3 minutes,Occurred : 1/29/2017 10:34 (Entered as : 01/2...,http://www.nuforc.org/webreports/132/S132369.html,Two erratic bright white lights seen in Southe...,2017-02-03T00:00:00,34.138265,-118.392057
8,There was only one UFO. It was yellow orange-...,Hernando,FL,2017-01-25T22:45:00,light,1 minute,Occurred : 1/25/2017 22:45 (Entered as : 1/25...,http://www.nuforc.org/webreports/132/S132302.html,There was only one UFO. It was yellow orange-...,2017-02-03T00:00:00,28.935600,-82.389500
10,"Two UFOs over Rockville, MD. ((anonymous repo...",Rockville,MD,2017-03-17T02:00:00,changing,5,Occurred : 3/17/2017 02:00 (Entered as : 3/17...,http://www.nuforc.org/webreports/133/S133154.html,"Two UFOs over Rockville, MD. The two object ap...",2017-03-17T00:00:00,39.077938,-77.149567
12,Bright falling object falls in a direct line t...,Redlands,CA,2017-03-13T20:50:00,oval,30 seconds,Occurred : 3/13/2017 20:50 (Entered as : 3/13...,http://www.nuforc.org/webreports/133/S133112.html,Bright falling object falls in a direct line t...,2017-03-17T00:00:00,34.030614,-117.149754
13,Friday march 10th 2017. There was a White ligh...,Alexandria,IN,2017-03-10T08:00:00,circle,30 minutes,Occurred : 3/10/2017 08:00 (Entered as : 3/10...,http://www.nuforc.org/webreports/133/S133094.html,"Friday, March 10th, 2017. There was a White l...",2017-03-17T00:00:00,40.249400,-85.670800
14,"A series of objects, approx. 30-50, flying in ...",O'Fallon,MO,2014-09-10T21:00:00,formation,30 minutes (?),Occurred : 9/10/2014 21:00 (Entered as : 09/1...,http://www.nuforc.org/webreports/133/S133081.html,"A series of objects, approx. 30-50, flying in ...",2017-03-17T00:00:00,38.825100,-90.728900
15,I want answers about this n,San Diego,CA,1989-07-20T18:00:00,cone,8-10 hours,Occurred : 7/20/1989 18:00 (Entered as : 0720...,http://www.nuforc.org/webreports/133/S133073.html,I want answers about this n This event happene...,2017-03-17T00:00:00,32.787229,-117.140268
16,Megatron in the bushes,Wellton,AZ,1994-09-01T20:00:00,unknown,1 hour,Occurred : 9/1/1994 20:00 (Entered as : 09019...,http://www.nuforc.org/webreports/132/S132593.html,"Megatron in the bushes In September 1994, I ha...",2017-02-17T00:00:00,32.700100,-114.175400
18,Saw a very large (size of a school bus) bright...,Kaneohe,HI,1998-01-24T05:45:00,triangle,5 hours,Occurred : 1/24/1998 05:45 Reported: 1/25/1998...,http://www.nuforc.org/webreports/003/S03048.html,Summary : Saw a very large (size of a school b...,1998-03-07T00:00:00,21.452630,-157.828446
21,"in the very early morning hours of 1962, I don...",Key West,FL,NaN,sphere,3 to 5 minutes,Occurred : 1/1/1962 08:00 (Entered as : 00/00...,http://www.nuforc.org/webreports/003/S03034.html,Summary : in the very early morning hours of 1...,NaN,24.584803,-81.683959
22,object seen moving from one star to another,Aurora,CO,NaN,light,5 sec.,Occurred : 6/1/1962 20:00 (Entered as : 1962)...,http://www.nuforc.org/webreports/003/S03037.html,Summary : object seen moving from one star to ...,NaN,39.680002,-104.792967
23,i dont remember going to my room but when i wo...,Waterville,ME,NaN,egg,10 MINS,Occurred : 3/15/1965 17:00 (Entered as : 3/?/...,http://www.nuforc.org/webreports/002/S02107.html,i dont remember going to my room but when i wo...,NaN,44.561366,-69.557749
24,Two objects rendevous at the moon.,San Lorenzo,CA,NaN,light,5-10 min,Occurred : 6/1/1965 21:00 (Entered as : 1965)...,http://www.nuforc.org/webreports/003/S03038.html,Summary : Two objects rendevous at the moon. J...,NaN,37.681000,-122.124400
26,My cousin & I were both 7 and we were behind o...,Carson City,MI,NaN,disk,5 minutes,Occurred : 6/1/1966 13:00 (Entered as : 1966)...,http://www.nuforc.org/webreports/002/S02112.html,Summary : My cousin & I were both 7 and we wer...,NaN,43.187600,-84.855100
27,5 objects seen over Sumner WA June of 1967. Ob...,Sumner,WA,NaN,formation,10-15 min,Occurred : 6/1/1967 21:00 Reported: 1/28/1998 ...,http://www.nuforc.org/webreports/003/S03057.html,Summary : 5 objects seen over Sumner WA June o...,NaN,47.172500,-122.184500
28,"no moon,observed colored blinking lights apox....",East Hanover,NJ,NaN,cigar,aprox.10min,Occurred : 7/1/1967 20:30 (Entered as : 7/xx/...,http://www.nuforc.org/webreports/003/S03025.html,"Summary : no moon,observed colored blinking li...",NaN,40.824000,-74.368700
30,A small UFO we chased in a Piper Cherokee plan...,Ironwood,MI,NaN,sphere,20 minutes,Occurred : 2/25/1968 22:00 Reported: 3/5/1997 ...,http://www.nuforc.org/webreports/002/S02050.html,Summary : A small UFO we chased in a Piper Che...,NaN,46.482300,-90.154000
31,I SEEN A UFO WHEN I WAS ABOUT 13 YEARS OLD. T...,Columbus,OH,1970-06-01T17:00:00,disk,1 OR 2 MIN.,Occurred : 6/1/1970 17:00 (Entered as : 1970)...,http://www.nuforc.org/webreports/002/S02121.html,Summary : I SEEN A UFO WHEN I WAS ABOUT 13 YE...,1998-03-07T00:00:00,40.003417,-82.998221
33,"1972,Utah-small bright cloud,I'm driving south...",Provo,UT,1972-07-01T19:00:00,disk,20-30 min.,Occurred : 7/1/1972 19:00 (Entered as : pre-d...,http://www.nuforc.org/webreports/001/S01893.html,"SUMMARY: 1972, Utah-small bright cloud, I'm d...",1998-03-07T00:00:00,40.271232,-111.624004
34,"Smooth, rounded triangular object, stone grey,...",Blackfoot,ID,1973-07-24T02:24:00,triangle,Approx. 4 minutes,Occurred : 7/24/1973 02:24 Reported: 3/19/1997...,http://www.nuforc.org/webreports/002/S02075.html,"Summary : Smooth, rounded triangular object, s...",1998-03-07T00:00:00,43.277900,-112.562700
35,A VERY fast light point object that was viewed...,Kittery,ME,1973-08-01T04:00:00,formation,10 Seconds,Occurred : 8/1/1973 04:00 (Entered as : 08/00...,http://www.nuforc.org/webreports/003/S03055.html,Summary : A VERY fast light point object that ...,1998-03-07T00:00:00,43.115300,-70.705100
36,I was 13-15. I was in my parent house on Moon...,Jamestown,NY,1975-01-01T03:00:00,sphere,a few minutes,Occurred : 1/1/1975 03:00 (Entered as : 1970'...,http://www.nuforc.org/webreports/002/S02166.html,Summary : I was 13-15. I was in my parent hou...,1998-03-07T00:00:00,42.104443,-79.251873
37,"My Father and I watched a silver object, shape...",Huntington Park,CA,1978-12-20T17:00:00,disk,20 min.,Occurred : 12/20/1978 17:00 Reported: 12/7/199...,http://www.nuforc.org/webreports/001/S01887.html,SUMMARY: My Father and I watched a silver obj...,1998-03-07T00:00:00,33.977500,-118.213300
38,"A huge solid black mass, silently glided direc...",Chico,CA,1979-07-01T03:00:00,rectangle,4 - 7 minutes,Occurred : 7/1/1979 03:00 (Entered as : 07/00...,http://www.nuforc.org/webreports/002/S02986.html,"Summary : A huge solid black mass, silently gl...",1998-03-07T00:00:00,39.776389,-121.827596

In [11]:
ufo_locs.to_csv('ufo_sighting_locations.csv')